const productsDB = [
  {
    modelName: "CRUSADER Acoustic DADDARIO-EZ910 Guitar String (6 Strings)",
    modelNo: "DADDARIO-EZ910",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/jgv5jm80/acoustic-guitar/s/x/6/ez910-11-52-daddario-original-imaezjz5kmehqhnx.jpeg",
    rating: { "5": 92, "4": 47, "3": 15, "2": 5, "1": 9 },
    avgRating: 4.2,
    noOfRatings: 168,
    noOfReviews: 16,
    price: 1900,
    discount: 77,
    discountedPrice: 499,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 3,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "MUSICREVOLUTION",
    sellerRating: 3.7,
    description: "The D'Addario EZ910 American Bronze acoustic guitar strings, which offer bright tone with great sustain. They combine the brilliance of 80/20 Bronze with the tonal characteristics of Phosphor Bronze. D'Addario is the world's largest manufacturer of strings for musical instruments. Many top guitarists won't play any other Brand. Regardless of your playing style, D'Addario has a set of strings that's right for your acoustic guitar.D'Addario EZ910 American Bronze Gauges 11-15-24-32-42-52",
    specifications:
      [
        { label: "Number of strings", value: "6" },
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "CRUSADER" },
        { label: "Color", value: "Orange" },
        { label: "Type", value: "Acoustic" },
        { label: "Core material", value: "BRONZE" },
        { label: "Generic name", value: "Guitar String" },
        { label: "Country of origin", value: "United States" }
      ]
  },
  {
    modelName: "FENDER FA125 Mahogany Acoustic Guitar (Natural)",
    modelNo: "FA125",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/jx3kn0w0/acoustic-guitar/n/g/j/fa125-fender-original-imafhmu9vyxfvtph.jpeg",
    rating: {},
    avgRating: 3.8,
    noOfRatings: 0,
    noOfReviews: 0,
    price: 12883,
    discount: 0,
    discountedPrice: 12883,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No cost EMI ₹2,148/month. Standard EMI also available View Plans"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "NIRVANA MUSIC INDIA",
    sellerRating: 1,
    description: "The Fender FA-125 is a visually beautiful guitar with a budget-friendly cost. Its quality laminate structure with a modern Fender 3+3 headstock and Viking bridge design an easy-playing instrument that plays great. Beginners and improving players will recognise this guitar, which emphasises a nato neck that transfers the guitar a lively tone and a soft playing feel.",
    specifications: [

      { label: "Sales Package", value: "1" },
      { label: "Brand", value: "FENDER" },
      { label: "Type", value: "Acoustic Guitar" },
      { label: "Number of Strings", value: "6" },
      { label: "Body Material", value: "Mahogany" },
      { label: "Fret Board Material", value: "Rosewood" },
      { label: "String Material", value: "Bronze" },
      { label: "Color", value: "Brown" },
      { label: "Number of Frets", value: "20" },
      { label: "Neck Material", value: "Mahogany" },
      { label: "Width", value: "40 cm" },
      { label: "Length", value: "105 cm" },
      { label: "Thickness", value: "18 cm" },
      { label: "Weight", value: "4.5 kg" },
      { label: "Generic Name", value: "Acoustic Guitars" },
      { label: "Country of origin", value: "India" }
    ]
  },
  {
    modelName: "CIERGE HEAVY PADDED (US ARMY PATTERN) Guitar Bag",
    modelNo: "HEAVY PADDED (US ARMY PATTERN)",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/jz7az680/instrument-bag/h/a/b/heavy-padded-guitar-bag-us-army-pattern-cierge-original-imafj9hfzdny6qpd.jpeg",
    rating: { "5": 518, "4": 211, "3": 83, "2": 23, "1": 40 },
    avgRating: 4.3,
    noOfRatings: 875,
    noOfReviews: 173,
    price: 1999,
    discount: 77,
    discountedPrice: 453,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "SWASTIKAUTHRIZED",
    sellerRating: 4,
    description: "",
    specifications:
      [
        { label: "Sales Package", value: "1" },
        { label: "Brand", value: "CIERGE" },
        { label: "Color", value: "Multicolor" },
        { label: "Material", value: "Polyethene" },
        { label: "Padded", value: "Yes" },
        { label: "Straps", value: "Yes" },
        { label: "Number of Pockets", value: "2" },
        { label: "Length", value: "110 cm" },
        { label: "Width", value: "43.2 cm" },
        { label: "Depth", value: "10.5 cm" },
        { label: "Weight", value: "0.55 g" },
        { label: "Generic Name", value: "Instrument Bags" },
        { label: "Country of origin", value: "India" }
      ]
  },
  {
    modelName: "KADENCE KAD-FNTR-SUN-EQ Linden Wood Acoustic Guitar  (sunburst)",
    modelNo: "KAD-FNTR-SUN-EQ",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/kb1470w0/acoustic-guitar/p/j/z/kad-fntr-sun-eq-kadence-original-imafsgywgcbrj6t6.jpeg",
    rating: { "5": 5, "4": 4, "3": 2, "2": 0, "1": 1 },
    avgRating: 4,
    noOfRatings: 12,
    noOfReviews: 2,
    price: 6540,
    discount: 1,
    discountedPrice: 6480,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "Bank Offer 5% off upto ₹25 on any prepaid instrument T&C", "No cost EMI ₹1,080/month. Standard EMI also available View Plans"],
    deliveryWithin: 9,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "satyaexim",
    sellerRating: 4.3,
    description: "",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "KADENCE" },
        { label: "Type", value: "Acoustic Guitar" },
        { label: "Number of strings", value: "6" },
        { label: "Body material", value: "Linden Wood" },
        { label: "Fret board material", value: "Rosewood" },
        { label: "String Material", value: "Steel" },
        { label: "Color", value: "Beige" },
        { label: "Pickup Present", value: "Yes" },
        { label: "Number of frets", value: "21" },
        { label: "Hand orientation", value: "Right" },
        { label: "Neck material", value: "lindon wood" },
        { label: "Width", value: "43 cm" },
        { label: "Length", value: "100 cm" },
        { label: "Thickness", value: "17 cm" },
        { label: "Weight", value: "2 kg" },
        { label: "Generic Name", value: "Acoustic Guitars" },
        { label: "Country of origin", value: "China" }
      ]
  },
  {
    modelName: "CRUSADER RED CAPO Spring Guitar Capo (RED)",
    modelNo: "CR-10",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/j9st5zk0/guitar-capo/t/m/s/cr-10-crusader-original-imaezhhyycbjyrqa.jpeg",
    rating: { "5": 181, "4": 63, "3": 37, "2": 8, "1": 16 },
    avgRating: 4.3,
    noOfRatings: 305,
    noOfReviews: 44,
    price: 700,
    discount: 74,
    discountedPrice: 179,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 3,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "MUSICREVOLUTION",
    sellerRating: 3.7,
    description: "",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "CRUSADER" },
        { label: "Type", value: "Standard" },
        { label: "Locking type", value: "Spring Guitar Capo" },
        { label: "Material", value: "METAL" },
        { label: "Color", value: "Red" },
        { label: "Used for", value: "Acoustic Guitars, Electric Guitars, Mandolins, 12-String Guitars, Classical Guitars" },
        { label: "finish", value: "GLOSS" },
        { label: "gripType", value: "YES" },
        { label: "singleHandOperated", value: "Yes" },
        { label: "Generic name", value: "Guitar Capo" },
        { label: "Country of origin", value: "China" }
      ]
  },
  {
    modelName: "AMG Music Guitar Picks with various Printed Design Set Of 6 Guitar Pick  (Pack of 6)",
    modelNo: "Guitar Picks with various Printed Design",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/kkcwo7k0/guitar-pick/x/l/g/guitar-picks-with-various-printed-design-set-of-6-6-amg-music-original-imafzq794mzfnvux.jpeg",
    rating: {},
    avgRating: 0,
    noOfRatings: 0,
    noOfReviews: 0,
    price: 599,
    discount: 58,
    discountedPrice: 249,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "Bank Offer5% off upto ₹25 on any prepaid instrumentT&C", "Bank Offer 5% off upto ₹25 on any prepaid instrument T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 3,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "ShopOngoods",
    sellerRating: 4,
    description: "Smooth Edges The picks feature a triangle shape with smooth edges. These are to be held between your thumb and index finger and played with the sharp end of the triangle strumming the strings. Anti-Slip Texture One of the most important features of a guitar pick is its texture and grip. These ergonomically designed picks provide the musician with a firm grip and prevent slipping from the hand during a show.",
    specifications:
      [
        { label: "Sales package", value: "6" },
        { label: "Brand", value: "AMG Music" },
        { label: "Type", value: "Standard Flat" },
        { label: "Material", value: "PVC (Polyvinyl Chloride)" },
        { label: "Shape", value: "Equilateral Triangle" },
        { label: "Color", value: "Multicolor" },
        { label: "Tip shape", value: "Round" },
        { label: "Pattern present", value: "Yes" },
        { label: "Grip present", value: "Yes" },
        { label: "Suitable for", value: "Acoustic Guitar, Classic Guitar, Electric Guitar" },
        { label: "Finish", value: "NA" },
        { label: "Pattern", value: "Skull" },
        { label: "Generic Name", value: "Guitar Pick" },
        { label: "Country of origin", value: "India" }
      ]
  },
  {
    modelName: "KADENCE KAD-A-06-EQ Ash Acoustic Guitar  (Brown)",
    modelNo: "KAD-A-06-EQ",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/kgsb1jk0/acoustic-guitar/d/j/x/kad-a-06-eq-kadence-original-imafwxx9h3sszwhq.jpeg",
    rating: { "5": 18, "4": 6, "3": 5, "2": 1, "1": 4 },
    avgRating: 4,
    noOfRatings: 34,
    noOfReviews: 8,
    price: 15000,
    discount: 52,
    discountedPrice: 7199,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "Bank Offer 5% off upto ₹25 on any prepaid instrument T&C", "No cost EMI ₹1,200/month. Standard EMI also available View Plans"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "satyaexim",
    sellerRating: 4.3,
    description: "From the house of Kadence comes the Acoustica series. These acoustic guitars are built to have great sound quality, high durability and increased ease of use for both beginners as well as professionals. The 39 inch stature makes it easy to handle and carry around without compromising on the sound quality. The selected Body woods allows for a high fidelity resonating hollow chamber and the rosewood fretboard makes is very durable with great sound carrying capabilities. If you are looking for a great quality acoustic guitar the Acosutic Series from Kadence is what you need",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "KADENCE" },
        { label: "Type", value: "Acoustic Guitar" },
        { label: "Number of Strings", value: "6" },
        { label: "Body material", value: "Ash" },
        { label: "Fret board material", value: "Rosewood" },
        { label: "String material", value: "Stainless Steel" },
        { label: "Color", value: "Brown" },
        { label: "Pickup present", value: "Yes" },
        { label: "Number of frets", value: "21" },
        { label: "Hand orientation", value: "Right" },
        { label: "Style", value: "Cut Away" },
        { label: "Tuner included", value: "Yes" },
        { label: "Pick included", value: "Yes" },
        { label: "Neck Material", value: "Maple" },
        { label: "Width", value: "43 cm" },
        { label: "Length", value: "100 cm" },
        { label: "Thickness", value: "17 cm" },
        { label: "Weight", value: "2.5 kg" },
        { label: "Fret board length", value: "38 cm" },
        { label: "Generic Name", value: "Acoustic Guitars" },
        { label: "Country of origin", value: "China" }
      ]
  },
  {
    modelName: "CRUSADER A Frame Stand (Used for: Acoustic Guitar)",
    modelNo: "LONG NECK",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/jihqljk0/guitar-stand/h/v/9/long-neck-crusader-original-imaf6a4p2fanzchm.jpeg",
    rating: { "5": 66, "4": 32, "3": 20, "2": 8, 1: "3" },
    avgRating: 4.2,
    noOfRatings: 129,
    noOfReviews: 16,
    price: 1760,
    discount: 66,
    discountedPrice: 598,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "Bank Offer 5% off upto ₹25 on any prepaid instrument T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "MUSICREVOLUTION",
    sellerRating: 3.7,
    description: "Guitar stand compatible with electric, acoustic, and bass guitars Friction locking knob locks into 'V-groove' and prevents rotation Stepped yoke and solid steel rod with locking keyway Non-slip rubber end caps Heavy-duty sheet metal leg housing",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "CRUSADER" },
        { label: "Capacity", value: "1" },
        { label: "Guitar stand type", value: "A Frame" },
        { label: "Material", value: "Iron" },
        { label: "Adjustable height", value: "Yes" },
        { label: "Type", value: "Stand" },
        { label: "Foldable", value: "Yes" },
        { label: "Compatible with", value: "Acoustic Guitar" },
        { label: "Color", value: "Black" },
        { label: "Finish", value: "GLOSSY" },
        { label: "Non-slip base", value: "Yes" },
      ]
  },
  {
    modelName: "Right Gear T-2 Clip-On Automatic Digital Display Tuner Automatic Digital Tuner  (Chromatic: Yes, Black)",
    modelNo: "T-2",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/kltryq80/tuner/m/e/k/t-2-clip-on-automatic-digital-display-tuner-right-gear-original-imagyuwh3fvfhbdg.jpeg",
    rating: { "5": 3, "4": 2, "3": 0, "2": 1, "1": 0 },
    avgRating: 4.2,
    noOfRatings: 6,
    noOfReviews: 0,
    price: 600,
    discount: 50,
    discountedPrice: 299,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "Bank Offer 5% off upto ₹25 on any prepaid instrument T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "eResults",
    sellerRating: 3.7,
    description: "Turning 360 degree freely. Adjustable view angle. A large LCD screen. Full color display. Super anti-interference. Handy compact digital clip-on style. Tuner picks up the sound by vibration. Easy to clip onto any stringed instrument. Sensitive and stable. Tuning Pitch Indicator Light: In flat: Indicator to the left and LCD screen turns red; In sharp: Indicator to the right and LCD screen turns yellow; In tune: Indicator to the middle and LCD screen turns green.",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "Right Gear" },
        { label: "Clip on", value: "Automatic Digital Display Tuner" },
        { label: "Type", value: "Digital" },
        { label: "Compatible with", value: "Acoustic Guitar, Electric Guitar, Ukulele, Banjo, Cello, Bass Guitar" },
        { label: "Chromatic", value: "Yes" },
        { label: "Tuning mode", value: "Automatic" },
        { label: "Display type", value: "LED" },
        { label: "Tuning range", value: "A, B, D, E , G" },
        { label: "Color", value: "Black" },
        { label: "Suitable for", value: "Acoustic Guitar Electric Guitar Banjo Ukulele Bass Guitar Cello" },
        { label: "Backlight present", value: "Yes" }
      ]
  },
  {
    modelName: "Juarez JRZ-ST01-SB Electric Guitar, With Case Electro-acoustic Guitar (Sun Burst)",
    modelNo: "JRZ-ST01-SB",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/jj4ln680/electric-guitar/x/g/j/jrz-st01-sb-electric-guitar-without-case-juarez-original-imaf6rjfcsetyysd.jpeg",
    rating: { "5": 10, "4": 8, "3": 3, "2": 2, "1": 3 },
    avgRating: 3.8,
    noOfRatings: 26,
    noOfReviews: 6,
    price: 14990,
    discount: 63,
    discountedPrice: 5523,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No cost EMI ₹921/month. Standard EMI also available View Plans"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "Omni Tech Retail",
    sellerRating: 4.5,
    description: "",
    specifications: []
  },
  {
    modelName: "MUSTANG Nylon Strap (Multicolor)",
    modelNo: "Guitar Straps",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/k2urhjk0/instrument-strap/w/z/y/guitar-straps-mustang-original-imafm3gbt4taxewd.jpeg",
    rating: { "5": 14, "4": 8, "3": 1, "2": 0, "1": 0 },
    avgRating: 4.6,
    noOfRatings: 23,
    noOfReviews: 2,
    price: 699,
    discount: 58,
    discountedPrice: 289,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No Cost EMI on Flipkart Axis Bank Credit Card T&C"],
    deliveryWithin: 3,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "MUSICREVOLUTION",
    sellerRating: 3.7,
    description: "",
    specifications:
      [
        { label: "Sales package", value: "1" },
        { label: "Brand", value: "MUSTANG" },
        { label: "Color", value: "Multicolor" },
        { label: "Material", value: "Nylon" },
        { label: "Designed for", value: "Guitar" },
        { label: "Attachment type", value: "BUCKLE" },
        { label: "Adjustable", value: "Yes" },
        { label: "Reversible", value: "Yes" },
        { label: "Length", value: "40 cm" },
        { label: "Width", value: "6 cm" },
        { label: "Generic Name", value: "Instrument Strap" },
        { label: "Country of origin", value: "India" }
      ]
  },
  {
    modelName: "Givson GS 1000 Electro-acoustic Guitar",
    modelNo: "GS 1000",
    imageUrl: "https://rukminim1.flixcart.com/image/416/416/electric-guitar/t/t/m/gs-1000-givson-original-imaeffbfbfpcu2ts.jpeg",
    rating: { "5": 11, "4": 2, "3": 1, "2": 2, "1": 6 },
    avgRating: 3.5,
    noOfRatings: 22,
    noOfReviews: 3,
    price: 15000,
    discount: 50,
    discountedPrice: 7499,
    offers: ["Bank Offer 5% Unlimited Cashback on Flipkart Axis Bank Credit Card T&C", "No cost EMI ₹1,250/month. Standard EMI also available View Plans"],
    deliveryWithin: 7,
    services: ["10 Days Replacement Policy", "Cash on Delivery available"],
    seller: "CREATIVE MUSIC",
    sellerRating: 4.3,
    description: "Want to recreate the magic of ‘70s with the epic song Hotel California by The Eagles? Then, make sure you have this GS 1000 electro-acoustic guitar from Givson at your disposal to set the mood for your listeners.Durable and Stylish Made of sturdy materials, this 6-stringed guitar is not just durable, but extremely stylish as well.",
    specifications: []
  },
]

module.exports = productsDB;